name: Build on main

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        run: |
          composer install
          npm install
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config push.default current
          git checkout -b release/main
          npm run build
          git add --force public/build
          git commit -m "build"
          git push origin release/main --force
